#!/bin/bash

array=()
array=(
http://www.berlitz.co.jp/lc/omotesando.html
http://www.berlitz.co.jp/lc/akasaka.html
http://www.berlitz.co.jp/lc/akabane.html
http://www.berlitz.co.jp/lc/ikebukuro.html
http://www.berlitz.co.jp/lc/ichigaya.html
http://www.berlitz.co.jp/lc/ueno.html
http://www.berlitz.co.jp/lc/otemachi.html
http://www.berlitz.co.jp/lc/ochanomizu.html
http://www.berlitz.co.jp/lc/kichijoji.html
http://www.berlitz.co.jp/lc/sangenjaya.html
http://www.berlitz.co.jp/lc/shinagawa.html
http://www.berlitz.co.jp/lc/shibuya.html
http://www.berlitz.co.jp/lc/shimokitazawa.html
http://www.berlitz.co.jp/lc/jiyugaoka.html
http://www.berlitz.co.jp/lc/shinaoyama.html
http://www.berlitz.co.jp/lc/shinjuku.html
http://www.berlitz.co.jp/lc/seijo.html
http://www.berlitz.co.jp/lc/shinyurigaoka.html
http://www.berlitz.co.jp/lc/tachikawa.html
http://www.berlitz.co.jp/lc/tamacenter.html
http://www.berlitz.co.jp/lc/chofu.html
http://www.berlitz.co.jp/lc/nakameguro.html
http://www.berlitz.co.jp/lc/nihonbashi.html
http://www.berlitz.co.jp/lc/nerima.html
http://www.berlitz.co.jp/lc/hamamatsucho.html
http://www.berlitz.co.jp/lc/machida.html
http://www.berlitz.co.jp/lc/meguro.html
http://www.berlitz.co.jp/lc/tokyo.html
http://www.berlitz.co.jp/lc/yurakucho.html
http://www.berlitz.co.jp/lc/roppongi.html
http://www.berlitz.co.jp/lc/aobadai.html
http://www.berlitz.co.jp/lc/atsugi.html
http://www.berlitz.co.jp/lc/kawasaki.html
http://www.berlitz.co.jp/lc/shinyokohama.html
http://www.berlitz.co.jp/lc/tamaplaza.html
http://www.berlitz.co.jp/lc/fujisawa.html
http://www.berlitz.co.jp/lc/mizonokuchi.html
http://www.berlitz.co.jp/lc/yokohama.html
http://www.berlitz.co.jp/lc/ichikawa.html
http://www.berlitz.co.jp/lc/kashiwa.html
http://www.berlitz.co.jp/lc/chiba.html
http://www.berlitz.co.jp/lc/omiya.html
http://www.berlitz.co.jp/lc/kariya.html
http://www.berlitz.co.jp/lc/toyota.html
http://www.berlitz.co.jp/lc/nagoyaekimae.html
http://www.berlitz.co.jp/lc/nagoyakanayama.html
http://www.berlitz.co.jp/lc/nagoyasakae.html
http://www.berlitz.co.jp/lc/hamamatsu.html
http://www.berlitz.co.jp/lc/shizuoka.html
http://www.berlitz.co.jp/lc/umeda.html
http://www.berlitz.co.jp/lc/senrichuo.html
http://www.berlitz.co.jp/lc/tennoji.html
http://www.berlitz.co.jp/lc/namba.html
http://www.berlitz.co.jp/lc/honmachi.html
http://www.berlitz.co.jp/lc/ashiya.html
http://www.berlitz.co.jp/lc/sannomiya.html
http://www.berlitz.co.jp/lc/nishinomiya.html
http://www.berlitz.co.jp/lc/kyotoekimae.html
http://www.berlitz.co.jp/lc/kyotoshijo.html
http://www.berlitz.co.jp/lc/sendai.html
http://www.berlitz.co.jp/lc/hiroshima.html
http://www.berlitz.co.jp/lc/okayama.html
)

for (( i=0; i<${#array[@]}; ++i ))
do
    casperjs ../scraper/berlitz.js ${array[$i]} >> ../scraped_result/content_BER.txt
done

