#!/bin/bash

array=()
array=(
http://www.cocojuku.jp/classroom/detail/1
http://www.cocojuku.jp/classroom/detail/2
http://www.cocojuku.jp/classroom/detail/3
http://www.cocojuku.jp/classroom/detail/5
http://www.cocojuku.jp/classroom/detail/7
http://www.cocojuku.jp/classroom/detail/4
http://www.cocojuku.jp/classroom/detail/6
http://www.cocojuku.jp/classroom/detail/8
http://www.cocojuku.jp/classroom/detail/27
http://www.cocojuku.jp/classroom/detail/28
http://www.cocojuku.jp/classroom/detail/26
http://www.cocojuku.jp/classroom/detail/29
http://www.cocojuku.jp/classroom/detail/31
http://www.cocojuku.jp/classroom/detail/32
http://www.cocojuku.jp/classroom/detail/30
http://www.cocojuku.jp/classroom/detail/33
http://www.cocojuku.jp/classroom/detail/36
http://www.cocojuku.jp/classroom/detail/35
http://www.cocojuku.jp/classroom/detail/34
http://www.cocojuku.jp/classroom/detail/37
http://www.cocojuku.jp/classroom/detail/38
http://www.cocojuku.jp/classroom/detail/39
http://www.cocojuku.jp/classroom/detail/41
http://www.cocojuku.jp/classroom/detail/40
http://www.cocojuku.jp/classroom/detail/42
http://www.cocojuku.jp/classroom/detail/10
http://www.cocojuku.jp/classroom/detail/9
http://www.cocojuku.jp/classroom/detail/11
http://www.cocojuku.jp/classroom/detail/12
http://www.cocojuku.jp/classroom/detail/14
http://www.cocojuku.jp/classroom/detail/13
http://www.cocojuku.jp/classroom/detail/18
http://www.cocojuku.jp/classroom/detail/19
http://www.cocojuku.jp/classroom/detail/16
http://www.cocojuku.jp/classroom/detail/15
http://www.cocojuku.jp/classroom/detail/21
http://www.cocojuku.jp/classroom/detail/20
http://www.cocojuku.jp/classroom/detail/17
http://www.cocojuku.jp/classroom/detail/24
http://www.cocojuku.jp/classroom/detail/23
http://www.cocojuku.jp/classroom/detail/22
http://www.cocojuku.jp/classroom/detail/25
http://www.cocojuku.jp/classroom/detail/43
http://www.cocojuku.jp/classroom/detail/44
http://www.cocojuku.jp/classroom/detail/47
http://www.cocojuku.jp/classroom/detail/48
http://www.cocojuku.jp/classroom/detail/49
http://www.cocojuku.jp/classroom/detail/45
http://www.cocojuku.jp/classroom/detail/46
http://www.cocojuku.jp/classroom/detail/50
http://www.cocojuku.jp/classroom/detail/51
http://www.cocojuku.jp/classroom/detail/52
http://www.cocojuku.jp/classroom/detail/53
http://www.cocojuku.jp/classroom/detail/54
http://www.cocojuku.jp/classroom/detail/55
http://www.cocojuku.jp/classroom/detail/56
http://www.cocojuku.jp/classroom/detail/63
http://www.cocojuku.jp/classroom/detail/58
http://www.cocojuku.jp/classroom/detail/57
http://www.cocojuku.jp/classroom/detail/59
http://www.cocojuku.jp/classroom/detail/62
http://www.cocojuku.jp/classroom/detail/60
http://www.cocojuku.jp/classroom/detail/61
http://www.cocojuku.jp/classroom/detail/64
http://www.cocojuku.jp/classroom/detail/65
http://www.cocojuku.jp/classroom/detail/66
http://www.cocojuku.jp/classroom/detail/67
http://www.cocojuku.jp/classroom/detail/68
http://www.cocojuku.jp/classroom/detail/70
http://www.cocojuku.jp/classroom/detail/69
http://www.cocojuku.jp/classroom/detail/71
http://www.cocojuku.jp/classroom/detail/72
http://www.cocojuku.jp/classroom/detail/73
http://www.cocojuku.jp/classroom/detail/75
http://www.cocojuku.jp/classroom/detail/76
http://www.cocojuku.jp/classroom/detail/77
http://www.cocojuku.jp/classroom/detail/74
http://www.cocojuku.jp/classroom/detail/78
http://www.cocojuku.jp/classroom/detail/79
http://www.cocojuku.jp/classroom/detail/80
)

for (( i=0; i<${#array[@]}; ++i ))
do
    casperjs ../scraper/coco.js ${array[$i]} >> ../content_coco.txt
done

